name: Recipe cron job
on:
  schedule:
   - cron: '0 17 * * 6'
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Recipe cron job
        run: |
          curl --request GET \
          --url 'https://snack-whiz.vercel.app/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_TOKEN }}'
